language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - black ./
  - flake8 --max-line-length=130 --ignore=F405,F403,F541,W503,E231,E722,F401,E501,F821
  # - flake8 --extend-ignore=E1,E23 .
  - coverage run --source=ebdjango,polls manage.py test

after_success:
  coveralls
